=== rakipv/wsd_cat2/technovid.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="christ">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="computer-science" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="stu-name"  type="MyName" ></xs:element>
                        <xs:element name="stu-university" type="MyCollege"></xs:element>
                        <xs:element name="stu-phone" type="MyContact"></xs:element>
                        <xs:element name="stu-email" type="MyEmail"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>


<xs:simpleType name="MyName">
    <xs:restriction base="xs:string" >
        <xs:pattern value = "[a-zA-Z]*"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="MyCollege">
    <xs:restriction base="xs:string" >
        <xs:pattern value = "[a-zA-Z]* [a-zA-Z]*"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="MyContact">
    <xs:restriction base="xs:integer">
        <xs:pattern value="\d{10}"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name = "MyEmail">
    <xs:restriction base = "xs:string">
        <xs:pattern value = "[0-9a-z]*@[a-z]*(university|college).(in|com)"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== rakipv/wsd_cat2/technovid.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="technovid.xsl"?>
<christ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="technovid.xsd">


    <computer-science>
        <stu-name>Amir</stu-name>
        <stu-university>Christ university</stu-university>
        <stu-phone>9632587412</stu-phone>
        <stu-email>amir@christuniversity.in</stu-email>
    </computer-science>

    <computer-science>
        <stu-name>Salmaan</stu-name>
        <stu-university>Christ university</stu-university>
        <stu-phone>8569741258</stu-phone>
        <stu-email>salmaan@christuniversity.in</stu-email>
    </computer-science>

    <computer-science>
        <stu-name>Sharuk</stu-name>
        <stu-university>Christ university</stu-university>
        <stu-phone>9856321475</stu-phone>
        <stu-email>sharuk@christuniversity.in</stu-email>
    </computer-science>
</christ>
